baseURL = '/'
relativeURLs = true
locale = 'en-us'
title = 'Awesomes'
ignoreLogs = ['warning-goldmark-raw-html']

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "aboust"
    name = "About"
    url = "/about"
    weight = 20
defaultContentLanguageInSubdir = true
