baseURL = '/'
relativeURLs = false
locale = 'en-us'
title = 'Awesomes'
ignoreLogs = ['warning-goldmark-raw-html']
disableKinds = ["rss","sitemap"]
disableLandingPage = false
[params]
  custom_css = ["css/style.css"]
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20
